[[language]]
name = "typescript"
file-types = ["ts","js"]
language-server = { command = "deno", args = ["lsp"]}
config = { deno = { enable = true, lint = true, unstable = true } }
auto-format = true
roots = ["deno.jsonc"]